// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALp6AvkqCM5G8zyiGQyqOaukIkfFWyJ34',
    appId: '1:73913717026:web:0bdb7bd002496fb401957b',
    messagingSenderId: '73913717026',
    projectId: 'flutterfirebasetutorial-a15e7',
    authDomain: 'flutterfirebasetutorial-a15e7.firebaseapp.com',
    storageBucket: 'flutterfirebasetutorial-a15e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgBzowPMBs-MpU5ofBm_6H8j3DnAxHKcA',
    appId: '1:73913717026:android:c3fc630a3eb31c4d01957b',
    messagingSenderId: '73913717026',
    projectId: 'flutterfirebasetutorial-a15e7',
    storageBucket: 'flutterfirebasetutorial-a15e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyX8nHdIPvBS0RKkUzTCQq0m6EJ1GboPA',
    appId: '1:73913717026:ios:938c75376e993e2001957b',
    messagingSenderId: '73913717026',
    projectId: 'flutterfirebasetutorial-a15e7',
    storageBucket: 'flutterfirebasetutorial-a15e7.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyX8nHdIPvBS0RKkUzTCQq0m6EJ1GboPA',
    appId: '1:73913717026:ios:938c75376e993e2001957b',
    messagingSenderId: '73913717026',
    projectId: 'flutterfirebasetutorial-a15e7',
    storageBucket: 'flutterfirebasetutorial-a15e7.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALp6AvkqCM5G8zyiGQyqOaukIkfFWyJ34',
    appId: '1:73913717026:web:bb323e7a4e9f0bc301957b',
    messagingSenderId: '73913717026',
    projectId: 'flutterfirebasetutorial-a15e7',
    authDomain: 'flutterfirebasetutorial-a15e7.firebaseapp.com',
    storageBucket: 'flutterfirebasetutorial-a15e7.firebasestorage.app',
  );
}
